"use client";
import { useMemo, useState } from "react";
type Product={id:number;name:string;category:string;type:string;price:number;color:string;tag?:string};
const products:Product[]=[{id:1,name:"Origin Varsity Jacket",category:"Men",type:"Varsity",price:285,color:"black",tag:"SIGNATURE"},{id:2,name:"Path Heavyweight Hoodie",category:"Women",type:"Hoodies",price:148,color:"cream",tag:"NEW"},{id:3,name:"Chimen Oversized Tee",category:"Men",type:"Tees",price:78,color:"white"},{id:4,name:"Legacy Sweatpant",category:"Women",type:"Sweatpants",price:128,color:"gray"},{id:5,name:"Mini Journey Hoodie",category:"Kids",type:"Hoodies",price:88,color:"acid",tag:"KIDS"},{id:6,name:"DJ Monogram Cap",category:"Unisex",type:"Caps",price:58,color:"black"},{id:7,name:"Route Utility Bag",category:"Unisex",type:"Accessories",price:115,color:"olive",tag:"LIMITED"},{id:8,name:"Youth Origin Tee",category:"Kids",type:"Tees",price:48,color:"cream"}];
const filters=["All","Men","Women","Kids","Hoodies","Varsity","Tees","Sweatpants","Caps","Accessories"];
export default function Home(){const[filter,setFilter]=useState("All"),[cart,setCart]=useState<Product[]>([]),[bag,setBag]=useState(false),[menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(""),[notice,setNotice]=useState("");const shown=useMemo(()=>products.filter(p=>(filter==="All"||p.category===filter||p.type===filter)&&p.name.toLowerCase().includes(query.toLowerCase())),[filter,query]);const add=(p:Product)=>{setCart(c=>[...c,p]);setNotice(`${p.name} added`);setTimeout(()=>setNotice(""),1800)};return <main>
<div className="announce">COMPLIMENTARY SHIPPING ON ORDERS $150+ <span>CHIMEN 001 — AVAILABLE NOW</span></div><header className="nav"><button className="menu" aria-label="Open menu" onClick={()=>setMenu(true)}>☰</button><a className="wordmark" href="#top">DJILEN<i /></a><nav><a href="#shop">MEN</a><a href="#shop">WOMEN</a><a href="#shop">KIDS</a><a href="#story">STORY</a></nav><div className="actions"><button onClick={()=>setSearch(!search)}>SEARCH</button><button onClick={()=>setBag(true)}>BAG ({cart.length})</button></div></header>{search&&<div className="searchbar"><input autoFocus placeholder="Search the collection..." value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>setSearch(false)}>CLOSE</button></div>}
<section className="hero" id="top"><div className="hero-art" aria-hidden="true"><div className="stamp">DJ<br/><span>001</span></div></div><div className="hero-copy"><p className="eyebrow">CHIMEN 001 / THE ORIGIN COLLECTION</p><h1>FIND<br/>YOUR <em>WAY.</em></h1><p>Premium streetwear shaped by culture, identity, and the roads that make us.</p><a className="cta" href="#shop">EXPLORE THE DROP <span>↗</span></a></div><p className="side-note">PORT-AU-PRINCE · NEW YORK · WORLDWIDE</p></section>
<section className="category-strip"><p>SHOP BY JOURNEY</p>{["MEN","WOMEN","KIDS"].map((x,i)=><a key={x} href="#shop" onClick={()=>setFilter(x[0]+x.slice(1).toLowerCase())}>{x} <span>0{i+1}</span></a>)}</section>
<section className="shop" id="shop"><div className="section-head"><div><p className="eyebrow dark">THE FULL DROP / 001</p><h2>NEW<br/><em>ARRIVALS</em></h2></div><p>Built with heavyweight fabrics, precise proportions, and symbols that carry the story forward.</p></div><div className="filters" role="group" aria-label="Product filters">{filters.map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="grid">{shown.map(p=><article className="product" key={p.id}><div className={`product-art ${p.color}`}><span className="mini-logo">DJ</span><span className="garment">{p.type==="Varsity"?"✦":p.type==="Caps"?"⌒":p.type==="Accessories"?"▰":"DJILEN"}</span>{p.tag&&<b>{p.tag}</b>}<button aria-label={`Add ${p.name} to bag`} onClick={()=>add(p)}>+</button><small>0{p.id}</small></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.category} / {p.type}</p></div><span>${p.price}</span></div></article>)}</div>{!shown.length&&<p className="empty">No pieces found on this path.</p>}</section>
<section className="featured"><div className="feature-art"><div className="jacket"><b>D</b><i>J</i><span>FIND YOUR WAY</span></div></div><div className="feature-copy"><p className="eyebrow">THE FOUNDER&apos;S PIECE</p><h2>ORIGIN<br/>VARSITY</h2><p>Cut from heavyweight wool with vegan leather sleeves. The embroidered path across the back marks where you started—not where you finish.</p><ul><li>Limited run of 100</li><li>Custom DJ hardware</li><li>Interior story label</li></ul><button onClick={()=>add(products[0])}>ADD TO BAG — $285 <span>↗</span></button></div></section>
<section className="manifesto" id="story"><p className="eyebrow">OUR STORY / NOU SE CHIMEN AN</p><blockquote>“Every path carries a story. <em>Wear yours.</em>”</blockquote><div className="story-grid"><p>DJILEN is born from the Haitian Creole idea of <strong>chimen</strong>—the road, the journey, the direction we choose. Each piece is a quiet marker of identity and movement.</p><p>Designed between Port-au-Prince and New York, our collections pair understated luxury with cultural memory. No clichés. Just intention, craft, and legacy.</p></div><a href="#shop">DISCOVER OUR JOURNEY ↗</a></section>
<section className="lookbook"><div className="look-card one"><span>01 / ORIGIN</span><b>MOVE<br/>WITH<br/>PURPOSE.</b></div><div className="look-card two"><span>02 / LEGACY</span><div className="monogram">D<span>J</span></div></div><div className="look-card three"><span>03 / FUTURE</span><b>THE ROAD<br/>IS YOURS.</b></div></section>
<section className="newsletter"><p className="eyebrow">THE DJILEN CIRCLE</p><h2>FOLLOW THE<br/><em>NEXT PATH.</em></h2><p>Early access to drops, private stories, and invitations from the journey.</p><form onSubmit={e=>{e.preventDefault();setNotice("Welcome to the journey")}}><input type="email" required placeholder="EMAIL ADDRESS"/><button>JOIN ↗</button></form></section>
<footer><a className="wordmark footmark" href="#top">DJILEN<i/></a><div><p>SHOP</p><a href="#shop">Men</a><a href="#shop">Women</a><a href="#shop">Kids</a><a href="#shop">Accessories</a></div><div><p>WORLD</p><a href="#story">Our story</a><a href="#">Journal</a><a href="#">Care</a><a href="#">Contact</a></div><div><p>FOLLOW</p><a href="#">Instagram</a><a href="#">TikTok</a><a href="#">Pinterest</a></div><small>© 2026 DJILEN. FIND YOUR WAY.</small></footer>
<aside className={`drawer ${bag?"open":""}`} aria-hidden={!bag}><div className="drawer-head"><b>YOUR BAG / {cart.length}</b><button onClick={()=>setBag(false)}>×</button></div>{cart.length===0?<div className="emptybag"><span>DJ</span><p>Your path is empty.</p><button onClick={()=>{setBag(false);location.hash="shop"}}>EXPLORE THE DROP</button></div>:<><div className="cart-items">{cart.map((p,i)=><div className="cart-row" key={`${p.id}-${i}`}><div className={`thumb ${p.color}`}>DJ</div><div><b>{p.name}</b><small>{p.category} / ONE SIZE</small><span>${p.price}</span></div><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}>REMOVE</button></div>)}</div><div className="checkout"><p>SUBTOTAL <b>${cart.reduce((s,p)=>s+p.price,0)}</b></p><button>CHECKOUT →</button></div></>}</aside>{(bag||menu)&&<button className="scrim" aria-label="Close panel" onClick={()=>{setBag(false);setMenu(false)}}/>}<aside className={`mobile-nav ${menu?"open":""}`}><button onClick={()=>setMenu(false)}>×</button><a href="#shop" onClick={()=>{setFilter("Men");setMenu(false)}}>MEN</a><a href="#shop" onClick={()=>{setFilter("Women");setMenu(false)}}>WOMEN</a><a href="#shop" onClick={()=>{setFilter("Kids");setMenu(false)}}>KIDS</a><a href="#story" onClick={()=>setMenu(false)}>STORY</a></aside>{notice&&<div className="toast">{notice} ✓</div>}</main>}
